### ISSUE TITLE
altname in GlyphData

### ISSUE THREAD

**Issue by schriftgestalt** [delucis/smufl-glyphs-info#3]
I had a look at the files. I don’t understand most of the package stuff ;)

To use the category/subCategory like this is unusual but should work.

But you don’t need the altName if it is the same as "uni"+Unicode.

**Comment by delucis** [comment]
Thanks for taking a look!

SMuFL defines 2790 codepoints, so I needed some way to break that up to keep track of all those glyphs!

Thanks for the tip about `altName`, I’ll remove it if it’s superfluous.

In case you’re curious, the package stuff does two things:

- [`lib/build.js`](https://github.com/delucis/smufl-glyphs-info/blob/master/lib/build.js) converts the JSON provided by the SMuFL specification into GlyphData.xml and Groups.plist
- [`bin/cli.js`](https://github.com/delucis/smufl-glyphs-info/blob/master/bin/cli.js) provides the command line tool for installing the files
